title: Roger Iyengar
description: >-
  I have completed my PhD in computer sceince. My thesis was Scaling Up Wearable
  Cognitive Assistance for Assembly Tasks.
url: "http://rogeriyengar.com"
address: []

remote_theme: github/personal-website
plugins:
  - jekyll-octicons
exclude:
  - LICENSE.txt
  - Gemfile
  - Gemfile.lock
  - CNAME

avatar: "/images/logo.png"
google_analytics: G-T6DK1C2YL6
lang: en

compress_html:
  clippings: all
  comments: all
