title: Roger Iyengar
description: >-
  I am pursuing my PhD in Computer Science at Carnegie Mellon University, where I have the
  privilege of being advised by Professor Satya.
url: "http://rogeriyengar.com"
address:
  - Gates Hillman Center 9221
  - Computer Science Department
  - Carnegie Mellon University

remote_theme: github/personal-website
plugins:
  - jekyll-octicons
exclude:
  - LICENSE.txt
  - Gemfile
  - Gemfile.lock
  - CNAME

avatar: "/images/logo.png"
google_analytics: G-T6DK1C2YL6
lang: en

compress_html:
  clippings: all
  comments: all
