title: Roger Iyengar
description: >-
  Research scientist at Meta.
url: "http://rogeriyengar.com"
address:
  - Meta
  - Bellevue, WA

remote_theme: github/personal-website
plugins:
  - jekyll-octicons
exclude:
  - LICENSE.txt
  - Gemfile
  - Gemfile.lock
  - CNAME

avatar: "/images/logo.png"
google_analytics: G-T6DK1C2YL6
lang: en

compress_html:
  clippings: all
  comments: all
